# Generated by Django 3.0.7 on 2020-06-08 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('Item_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('calories', models.IntegerField(default=2500)),
                ('price', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('age', models.IntegerField(default=25)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='django_app.Item')),
                ('caffeine', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.Menu'),
        ),
    ]
