# Generated by Django 3.0.7 on 2020-06-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_club_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='exp',
            field=models.PositiveIntegerField(verbose_name='Years of Experience'),
        ),
    ]
