# Generated by Django 3.0.7 on 2020-06-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_auto_20200622_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='DOJ',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='emp_photo',
            field=models.ImageField(null=True, upload_to='uploadsPerson/'),
        ),
    ]
